### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by xmnlab** [omnisci/ibis-omniscidb#18]
In the metapackage omnisci-datascience-tools we are shipping a lot of libraries, including ibis-framework.

That would be good to start to plan the first release for ibis-omniscidb and we can also include that to the plan for omnisci-datascience packages.

I think, from the package perspective, at least for what we need, the big block is the pinning for pymapd 0.24. We can create a package structure for what we have now .. and when the new ibis is released without pymapd/omnisci we can just update the recipe for the new structure.

@datapythonista do you have any  idea about when the ibis will be released?

**Comment by datapythonista** [comment]
The changes required to Ibis before releasoning will still take several weeks. I don't really know exactly, but there are many things that need to be fixed before (the entrypoints system requires the CI to be migrated to actions, and migrating to actions requires replacing impala from the tutorials, this alone will take a while).

**Comment by xmnlab** [comment]
I see, thanks for the explanation. 

PS: I am going to keep this issue open until we have the first release.

**Comment by xmnlab** [comment]
`ibis-omniscidb` already available from https://pypi.org/project/ibis-omniscidb/
For now, it can be imported using `import ibis_omniscidb`. 

conda package on conda-forge in progress https://github.com/conda-forge/staged-recipes/pull/14114

**Comment by xmnlab** [comment]
conda forge package available https://github.com/conda-forge/ibis-omniscidb-feedstock
