### ISSUE TITLE
current_database should return live info rather than input parameter

### ISSUE THREAD

**Issue by mikehinchey** [omnisci/ibis-omniscidb#21]
Since a connection can be created with the user's default database, or from a session_id, the `self.db_name` is not always accurate. Can we change the `current_database` function to get the database from the session_info as below?

```python
return self.con._client.get_session_info(self.con._session).database
```

https://github.com/omnisci/ibis-omniscidb/blob/d38992d9268a7eaffe2ba6163b48e1043d34a8c2/ibis_omniscidb/client.py#L1215

**Comment by xmnlab** [comment]
resolved by #32
