### ISSUE TITLE
Change to use pyomnisci instead of pymapd

### ISSUE THREAD

**Issue by mikehinchey** [omnisci/ibis-omniscidb#23]
There's new functionality in pyomnisci, so it would be good to use that instead of pymapd.

https://github.com/omnisci/pyomnisci

https://pypi.org/project/pyomnisci/

**Comment by xmnlab** [comment]
@mikehinchey I have a work in progress here: https://github.com/omnisci/ibis-omniscidb/pull/29/checks?check_run_id=1970318902

it seems that using pyomnisci from github master branch it is working. but from pypi it is not working. could we have a new release with the changes on master?

**Comment by jclay** [comment]
Hi @xmnlab we released v0.27.0 today. Please let me know if this resolves your issue. https://pypi.org/project/pyomnisci/0.27.0/

**Comment by xmnlab** [comment]
thanks @jclay ! I will move forward that PR. thank you so much!

**Comment by xmnlab** [comment]
It seems also it will need a new release for pyomniscidb as the current release is pinning rbc to 0.2.2 

https://github.com/omnisci/omniscidb/blob/v5.5.2/python/setup.py

and this version is using pymapd:

/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/rbc/omniscidb.py:8: in <module>
    from pymapd.cursor import make_row_results_set
E   ModuleNotFoundError: No module named 'pymapd'

any plans for a new release for `pyomniscidb`?
